_DMACODE EQU $FF80

_SECTION_LENGTH EQU $A0

_OAM_DATA EQU _RAM                 ; Must be a multiple of $100

_GAME_DATA EQU _OAM_DATA + _SECTION_LENGTH

_TEXT_BUFFER EQU _GAME_DATA + _SECTION_LENGTH

_TEXT_CONSTANTS EQU _TEXT_BUFFER + _SECTION_LENGTH


; i'm lazy
LEFT_BORDER EQU 8
RIGHT_BORDER EQU 160
TOP_BORDER EQU 8 + 8 + (2*8)
BOTTOM_BORDER EQU 144 + 8

; player can't go across the board.
P1_MAX_X EQU 80

PAD_SPEED EQU 2
MIN_BALL_SPEED EQU 1
MAX_BALL_SPEED EQU 7

BYTES_PER_TILE EQU 16
BYTES_PER_OBJECT EQU 32

TEXT_START_TILE_1 EQU 128

SCREEN_WIDTH_TILES EQU 20
CANVAS_WIDTH_TILES EQU 32
SCREEN_HEIGHT_TILES EQU 18
CANVAS_HEIGHT_TILES EQU 32
