_DMACODE EQU $FF80

_SECTION_LENGTH EQU $A0

_OAM_DATA EQU _RAM                 ; Must be a multiple of $100

_GAME_DATA EQU _OAM_DATA + _SECTION_LENGTH

_TEXT_BUFFER EQU _GAME_DATA + _SECTION_LENGTH

_TEXT_CONSTANTS EQU _TEXT_BUFFER + _SECTION_LENGTH

TEXT_OFFSET EQU 4

; i'm lazy
LEFT_BORDER EQU 8
RIGHT_BORDER EQU 160
TOP_BORDER EQU 8 + 8 + (2*8)
BOTTOM_BORDER EQU 144 + 8

BYTES_PER_TILE EQU 16
BYTES_PER_OBJECT EQU 32

; info for text drawing
P1_LABEL_OFFSET EQU 0
P1_LABEL_OFFSET_BYTES EQU P1_LABEL_OFFSET * BYTES_PER_TILE
P1_LABEL_SIZE EQU 3

P1_SCORE_OFFSET EQU 4
P1_SCORE_OFFSET_BYTES EQU P1_SCORE_OFFSET * BYTES_PER_TILE
P1_SCORE_SIZE EQU 3

P2_LABEL_OFFSET EQU 11
P2_LABEL_OFFSET_BYTES EQU P2_LABEL_OFFSET * BYTES_PER_TILE
P2_LABEL_SIZE EQU 3

P2_SCORE_OFFSET EQU 15
P2_SCORE_OFFSET_BYTES EQU P2_SCORE_OFFSET * BYTES_PER_TILE
P2_SCORE_SIZE EQU 3

TEXT_BUFFER_SIZE EQU $40

; player can't go across the board.
P1_MAX_X EQU 80

PAD_SPEED EQU 2
MIN_BALL_SPEED EQU 1
MAX_BALL_SPEED EQU 7

TEXT_START_TILE_1 EQU 128

SCREEN_WIDTH_TILES EQU 20
CANVAS_WIDTH_TILES EQU 32
SCREEN_HEIGHT_TILES EQU 18
CANVAS_HEIGHT_TILES EQU 32
